# Don't print a new line at the start of the prompt
add_newline = false

[aws]
style = "bold #ffb86c"

[character]
error_symbol = "[➜](bold #ff5555)"
success_symbol = "[➜](bold #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[time]
disabled =  false
time_format = "%H:%M:%S"
utc_time_offset = "-4"

# [hostname]
# style = "bold #bd93f9"
#
# [username]
# format = "[$user]($style) on "
# style_user = "bold #8be9fd"

# Replace the "❯" symbol in the prompt with "➜"
#[character]      # The name of the module we are configuring is "character"
#success_symbol = "[➜](bold green)"     # The "symbol" segment is being set to "➜"


# Use custom format
#format = """
#[┌───────────────────>](bold green)
#[│](bold green)$directory$rust$package
#[└─>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
#scan_timeout = 10
# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true
