require ('packmanager')
require ('settings')
require ('keybinds')
require	('augroup')
require ('statusline')
require ('complete')
require ('teles')
require ('lsp-config')
require ('treesitter')
require ('tree')
require ('comment')
require ('indent')
require ('luasnip.loaders.from_lua').load({paths = "~/.config/nvim/snippets"})
