[theme]
name = "dracula"
[icons]
name = "awesome6"

[[block]]
block = "disk_space"
path = "/home"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "networkmanager"
primary_only = false 
ap_format = "{ssid} {strength}%"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %B %d %Y %R"

[[block]]
block = "xrandr"
icons = false
resolution = true
interval = 2
